name: Auto-approve AWSSDK dependency updates
on:
  pull_request:
    types: [ opened, synchronize ]
permissions:
  pull-requests: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  renovate:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        if: contains(github.event.pull_request.title, 'AWSSDK')
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
