name: Auto-merge AWSSDK dependency updates
on:
  pull_request:
    types: [ opened, synchronize ]
permissions:
  pull-requests: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  renovate:
    if: startsWith(github.head_ref, 'renovate/') && contains(github.event.pull_request.title, 'AWSSDK')
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
